//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.hanyu.luckychild.ui.login;

import android.app.Activity;
import android.content.Context;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import com.hanyu.luckychild.R.id;
import com.hanyu.luckychild.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RegisterActivity_
    extends RegisterActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_reg);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RegisterActivity_.IntentBuilder_ intent(Context context) {
        return new RegisterActivity_.IntentBuilder_(context);
    }

    public static RegisterActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new RegisterActivity_.IntentBuilder_(fragment);
    }

    public static RegisterActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new RegisterActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        et_phone = ((EditText) hasViews.findViewById(id.et_phone));
        tv_reg = ((TextView) hasViews.findViewById(id.tv_reg));
        et_c_pwd = ((EditText) hasViews.findViewById(id.et_c_pwd));
        iv_back = ((ImageView) hasViews.findViewById(id.iv_back));
        et_job = ((EditText) hasViews.findViewById(id.et_job));
        et_pwd = ((EditText) hasViews.findViewById(id.et_pwd));
        et_code = ((EditText) hasViews.findViewById(id.et_code));
        if (iv_back!= null) {
            iv_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    RegisterActivity_.this.back();
                }

            }
            );
        }
        if (tv_reg!= null) {
            tv_reg.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    RegisterActivity_.this.Register();
                }

            }
            );
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<RegisterActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, RegisterActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), RegisterActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), RegisterActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

    }

}
