//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.hanyu.luckychild.ui.menu;

import android.app.Activity;
import android.content.Context;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.support.v4.view.ViewPager;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import com.hanyu.luckychild.R.id;
import com.hanyu.luckychild.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderActivity_
    extends OrderActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_order);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderActivity_.IntentBuilder_ intent(Context context) {
        return new OrderActivity_.IntentBuilder_(context);
    }

    public static OrderActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new OrderActivity_.IntentBuilder_(fragment);
    }

    public static OrderActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new OrderActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_finish = ((TextView) hasViews.findViewById(id.tv_finish));
        view_pager = ((ViewPager) hasViews.findViewById(id.view_pager));
        tv_wait_send = ((TextView) hasViews.findViewById(id.tv_wait_send));
        et_search = ((EditText) hasViews.findViewById(id.et_search));
        tv_wait_commit = ((TextView) hasViews.findViewById(id.tv_wait_commit));
        indicator_line = hasViews.findViewById(id.indicator_line);
        iv_right = ((ImageView) hasViews.findViewById(id.iv_right));
        tv_wait_get = ((TextView) hasViews.findViewById(id.tv_wait_get));
        iv_back = ((ImageView) hasViews.findViewById(id.iv_back));
        if (tv_wait_send!= null) {
            tv_wait_send.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.changePage2();
                }

            }
            );
        }
        if (iv_back!= null) {
            iv_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.back();
                }

            }
            );
        }
        if (iv_right!= null) {
            iv_right.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.codeOrder();
                }

            }
            );
        }
        if (tv_finish!= null) {
            tv_finish.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.changePage4();
                }

            }
            );
        }
        if (tv_wait_get!= null) {
            tv_wait_get.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.changePage3();
                }

            }
            );
        }
        if (tv_wait_commit!= null) {
            tv_wait_commit.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    OrderActivity_.this.changePage1();
                }

            }
            );
        }
        init();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<OrderActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, OrderActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), OrderActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), OrderActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

    }

}
